# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch: 
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.metrics_token }}
          output_action: gist
          committer_gist: ${{ secrets.METRICS_GIST }}

          # Options
          user: ThiBIAL
          template: classic
          base: header, activity, community, repositories, metadata
          config_order: base.header, introduction, base.activity+community, base.repositories, lines, languages, isocalendar
          config_timezone: Europe/Paris

          plugin_introduction: yes
          plugin_introduction_title: yes
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_languages_other: yes
          plugin_languages_colors: github
          plugin_languages_sections: most-used
          plugin_languages_details: percentage, bytes-size

          
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%

          plugin_lines: yes

          plugin_traffic: yes
